
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: {{ .Values.spec.destination.server }}
  project: default
  wordpress:
    wordpressPassword: foo
    mariadb:
      db:
        password: bar
      rootUser:
        password: baz
dependencies:
- name: wordpress
  version: 5.0.2
  repository: https://kubernetes-charts.storage.googleapis.com
